package com.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table smo_tags_relation
 */
public class SmoTagsRelation {
    /**
     * Database Column Remarks:
     *   自增id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smo_tags_relation.id
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   问题id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smo_tags_relation.tag_id
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    private Integer tagId;

    /**
     * Database Column Remarks:
     *   关联的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smo_tags_relation.relation_id
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    private Integer relationId;

    /**
     * Database Column Remarks:
     *   关联类型 1 关联问题包 2关联问题 3 关联分类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smo_tags_relation.relation_type
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    private Byte relationType;

    /**
     * Database Column Remarks:
     *   逻辑删除标记
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smo_tags_relation.is_delete
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    private Byte isDelete;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smo_tags_relation.created_at
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    private Date createdAt;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smo_tags_relation.updated_at
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smo_tags_relation.id
     *
     * @return the value of smo_tags_relation.id
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smo_tags_relation.id
     *
     * @param id the value for smo_tags_relation.id
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smo_tags_relation.tag_id
     *
     * @return the value of smo_tags_relation.tag_id
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smo_tags_relation.tag_id
     *
     * @param tagId the value for smo_tags_relation.tag_id
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smo_tags_relation.relation_id
     *
     * @return the value of smo_tags_relation.relation_id
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    public Integer getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smo_tags_relation.relation_id
     *
     * @param relationId the value for smo_tags_relation.relation_id
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    public void setRelationId(Integer relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smo_tags_relation.relation_type
     *
     * @return the value of smo_tags_relation.relation_type
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    public Byte getRelationType() {
        return relationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smo_tags_relation.relation_type
     *
     * @param relationType the value for smo_tags_relation.relation_type
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    public void setRelationType(Byte relationType) {
        this.relationType = relationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smo_tags_relation.is_delete
     *
     * @return the value of smo_tags_relation.is_delete
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smo_tags_relation.is_delete
     *
     * @param isDelete the value for smo_tags_relation.is_delete
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smo_tags_relation.created_at
     *
     * @return the value of smo_tags_relation.created_at
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smo_tags_relation.created_at
     *
     * @param createdAt the value for smo_tags_relation.created_at
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smo_tags_relation.updated_at
     *
     * @return the value of smo_tags_relation.updated_at
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smo_tags_relation.updated_at
     *
     * @param updatedAt the value for smo_tags_relation.updated_at
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}