package com.dao;

import com.model.SmoTagsRelation;
import java.util.List;

public interface SmoTagsRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smo_tags_relation
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smo_tags_relation
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    int insert(SmoTagsRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smo_tags_relation
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    SmoTagsRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smo_tags_relation
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    List<SmoTagsRelation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smo_tags_relation
     *
     * @mbg.generated Thu Apr 30 14:38:57 CST 2020
     */
    int updateByPrimaryKey(SmoTagsRelation record);
}